language: scala
scala:
  - 2.9.1
jdk:
  - openjdk7
env:
  - MODULE=zipkin-cassandra
  - MODULE=zipkin-collector-core
  - MODULE=zipkin-collector-scribe
  - MODULE=zipkin-collector-service
  - MODULE=zipkin-common
  - MODULE=zipkin-hadoop
  - MODULE=zipkin-job-runner
  - MODULE=zipkin-kafka
  - MODULE=zipkin-query-core
  - MODULE=zipkin-query-service
  - MODULE=zipkin-redis
  - MODULE=zipkin-scrooge
  - MODULE=zipkin-test
  - MODULE=zipkin-thrift
  - MODULE=zipkin-web
script: "env SBT_TRAVIS_CI=true bin/sbt \"project $MODULE\" test"
